name: Sync LeetCode

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs automatically every day at midnight

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run LeetCode Sync
        uses: zwfres/leetcode-synchronizer@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          leetcode-user: ${{ secrets.LEETCODE_USER }}
